# docker-compose.yml
# docker compose up
version: '3'
services:  

  cram-eurobin:
    image: "arthurniedz/cram:test"
    container_name: cram-eurobin-container
    # for windows and mac, use 'network_mode: bridge'
    # network_mode: host  
    ports:
      - 8888
    privileged: true
    environment:
      - DISPLAY
    #  - ROS_MASTER_URI=http://192.168.xxx.x:11311  
    volumes:
      - ./lectures:/home/lectures

  cram-demos:
    image: "arthurniedz/cram:devel"
    container_name: cram-devel-container
    # for windows and mac, use 'network_mode: bridge'
    network_mode: host  
    privileged: true
    environment:
      - DISPLAY
    #  - ROS_MASTER_URI=http://192.168.xxx.x:11311  
    volumes:
      - ./lectures:/home/lectures


  cram-lecture:
    image: "arthurniedz/cram:latest"
    container_name: cram-lecture-container
  # for windows and mac, use 'network_mode: bridge'
    network_mode: host  
    privileged: true
  ##############
  # BEGIN Remove 
  # Remove this section if docker-compose complains about network_mode: host and port forwarding on newer debian versions (22.04)
    ports:
      - "8888:8888"
    expose:
      - "8888"
  # END Remove
  ##############
    environment:
      - DISPLAY=${DISPLAY}
  # set to the Turtles IP      
  #    - ROS_MASTER_URI=http://192.168.xxx.x:11311  
    volumes:
      - ./lectures:/home/lectures


  cram-headless:
    image: "arthurniedz/cram:headless-1.3"
    container_name: cram-headless-container
    network_mode: host  
    privileged: true
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - ./lectures:/home/lectures
    # entrypoint: ./lectures/init.sh

  cram-jupyterhub:
    image: "cramteaching:jupyterhub-0.6"
    stdin_open: true
    tty: true
    # user: root
    # command: jupyter-lab --allow-root --no-browser --NotebookApp.token='' --port 8888 --ip=0.0.0.0
    command: jupyter-lab --no-browser --NotebookApp.token='' --port 8888 --ip=0.0.0.0
    working_dir: /home/jovyan/
    entrypoint: /home/jovyan/repo/binder/init.sh
    ports:
      - 8888:8888
      # - 9090:9090
    privileged: true
    # environment:
    #   - DISPLAY
    volumes:
      - ./:/home/jovyan/work
      # - ./lectures:/home/lectures
      # - /tmp/.X11-unix:/tmp/.X11-unix:rw
