version: '3'
services:  
  cram-binder:
    image: cramteaching:binderhub
    build:
      context: ../
      dockerfile: ./binder/Dockerfile
    stdin_open: true
    tty: true
    privileged: true
    # user: root
    entrypoint: /home/jovyan/cram_teaching/binder/entrypoint.sh
    command: jupyter lab --allow-root --NotebookApp.token='' --no-browser
    ports:
      - 8888:8888
    environment:
      - DISPLAY
      - QT_X11_NO_MITSHM=1
    volumes:
      - ../:/home/jovyan/cram_teaching
      - /tmp/.X11-unix:/tmp/.X11-unix:rw